config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  get '/terms' => 'pages#terms'
  get '/about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :contacts, only: [:new, :create], path_names: { :new => ''}
  resources :articles do
    resource :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, presence: true
  validates :body, presence: true
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def blank?
    !self.attributes.find do |key, value|
      case (key)
        when 'id', 'created_at', 'updated_at'
          false
      else
        value.present?
      end
    end
  end
  def index
    @articles = Article.all
  end
  def new
  end

  def create
    @article= Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: "new"
    end

  end
  def show
    @article = Article.find(params[:id])
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: "edit"
    end
  end
  def destroy
    @article = Article.find(params[:id])
    if @article
      if @article.destroy
        redirect_to articles_path
      end
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: "new"
    end

  end
  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms

  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br/>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<% @articles.each do |article| %>

  <h2>
    <%= article.title %>
  </h2>

  <p>
    <%= article.text %>
  </p>

  <p>
    <%= link_to 'Show', article_path(article) %> |
    <%= link_to 'Edit', edit_article_path(article) %> |
    <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %>

  </p>
  <hr>
<% end %>
<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>
<p class="danger">
  <% if @article && @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
      <span><%= msg %>&comma;&nbsp;</span>
    <% end %>
  <% end %>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br/>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1>Article</h1>
<hr>
<h2><%= @article.title %></h2>
<p><%= @article.text %></p>

<% @comments = @article.comments %>
<h2 style="font-style: italic">Comments</h2>
<hr>
<%= 'No comments' if @article.comments.empty?  %>
<% @comments.each do |comment| %>
  <span style="font-size: x-large; font-weight: bold">
    <%= comment.author %>
  </span>
  <span><i>said:</i></span>
   <p>
    <%= comment.body %>
  </p>
<% end %>
<h2 style="font-style: italic">Add Comment</h2>
<hr>
<%= form_for ([@article, @comments.build]) do |f| %>
  <p>
    <%= f.label :author %> <br/>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Add Comments'%>
  </p>
<% end %>
<hr/>
<%= link_to 'All Articles', articles_path %>

app/views/contacts/create.html.erb
<p>Thanks</p>

app/views/contacts/new.html.erb
<h1>Contact US</h1>


<%= form_for :contact, url: contacts_path do |f| %>
  <p class="danger">
    <% if @contact && @contact.errors.any? %>
      <% @contact.errors.full_messages.each do |msg| %>
         <span><%= msg %>&comma;&nbsp;</span>
      <% end %>
  <% end %>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :message %><br/>
    <%= f.text_area :message %>
  </p>
  <p>
    <%= f.submit 'Send Message' %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About US</h1>

app/views/pages/terms.html.erb
<h1>Terms & Conditions</h1>
<p></p>